version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "2222:2222"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:2222 &&
      celery -A app worker -l info"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

volumes:
  pgdata: